services:
  spanner-omni:
    image: us-docker.pkg.dev/spanner-omni/images/spanner-omni:2026.r1-beta
    command: start-single-server
    ports:
      - "127.0.0.1:15000:15000"
    volumes:
      - spanner:/spanner

volumes:
  spanner:
